// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using school_management_system.Models;

#nullable disable

namespace school_management_system.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GradeModelSubjectModel", b =>
                {
                    b.Property<int>("GradesId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectsId")
                        .HasColumnType("int");

                    b.HasKey("GradesId", "SubjectsId");

                    b.HasIndex("SubjectsId");

                    b.ToTable("GradeModelSubjectModel");
                });

            modelBuilder.Entity("GroupModelSubjectModel", b =>
                {
                    b.Property<int>("GroupsId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectsId")
                        .HasColumnType("int");

                    b.HasKey("GroupsId", "SubjectsId");

                    b.HasIndex("SubjectsId");

                    b.ToTable("GroupModelSubjectModel");
                });

            modelBuilder.Entity("GuardianModelStudentModel", b =>
                {
                    b.Property<int>("GuardiansId")
                        .HasColumnType("int");

                    b.Property<int>("StudentsId")
                        .HasColumnType("int");

                    b.HasKey("GuardiansId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("GuardianModelStudentModel");
                });

            modelBuilder.Entity("SubjectModelTeacherModel", b =>
                {
                    b.Property<int>("SubjectModelsId")
                        .HasColumnType("int");

                    b.Property<int>("TeachersId")
                        .HasColumnType("int");

                    b.HasKey("SubjectModelsId", "TeachersId");

                    b.HasIndex("TeachersId");

                    b.ToTable("SubjectModelTeacherModel");
                });

            modelBuilder.Entity("school_management_system.Models.AssessmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Assessment_TypeModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Assessment_TypeModelId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("school_management_system.Models.Assessment_TypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Assessmen_Types");
                });

            modelBuilder.Entity("school_management_system.Models.AuthModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("StudentModelId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherModelId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudentModelId");

                    b.HasIndex("TeacherModelId");

                    b.ToTable("Authotications");
                });

            modelBuilder.Entity("school_management_system.Models.ClassroomModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("school_management_system.Models.DepartmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("school_management_system.Models.GradeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentModelId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("school_management_system.Models.GroupModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassroomModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomModelId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("school_management_system.Models.GuardianModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Guardians");
                });

            modelBuilder.Entity("school_management_system.Models.MajorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubjectModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentModelId");

                    b.HasIndex("SubjectModelId");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("school_management_system.Models.RoleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthModelId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("school_management_system.Models.StudentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssessmentModelId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentModelId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("school_management_system.Models.SubjectModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssessmentModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentModelId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("school_management_system.Models.TeacherModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("GradeModelSubjectModel", b =>
                {
                    b.HasOne("school_management_system.Models.GradeModel", null)
                        .WithMany()
                        .HasForeignKey("GradesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("school_management_system.Models.SubjectModel", null)
                        .WithMany()
                        .HasForeignKey("SubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupModelSubjectModel", b =>
                {
                    b.HasOne("school_management_system.Models.GroupModel", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("school_management_system.Models.SubjectModel", null)
                        .WithMany()
                        .HasForeignKey("SubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuardianModelStudentModel", b =>
                {
                    b.HasOne("school_management_system.Models.GuardianModel", null)
                        .WithMany()
                        .HasForeignKey("GuardiansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("school_management_system.Models.StudentModel", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubjectModelTeacherModel", b =>
                {
                    b.HasOne("school_management_system.Models.SubjectModel", null)
                        .WithMany()
                        .HasForeignKey("SubjectModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("school_management_system.Models.TeacherModel", null)
                        .WithMany()
                        .HasForeignKey("TeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("school_management_system.Models.AssessmentModel", b =>
                {
                    b.HasOne("school_management_system.Models.Assessment_TypeModel", null)
                        .WithMany("Assessments")
                        .HasForeignKey("Assessment_TypeModelId");
                });

            modelBuilder.Entity("school_management_system.Models.AuthModel", b =>
                {
                    b.HasOne("school_management_system.Models.StudentModel", null)
                        .WithMany("Auths")
                        .HasForeignKey("StudentModelId");

                    b.HasOne("school_management_system.Models.TeacherModel", null)
                        .WithMany("AuthModels")
                        .HasForeignKey("TeacherModelId");
                });

            modelBuilder.Entity("school_management_system.Models.GradeModel", b =>
                {
                    b.HasOne("school_management_system.Models.StudentModel", null)
                        .WithMany("Grades")
                        .HasForeignKey("StudentModelId");
                });

            modelBuilder.Entity("school_management_system.Models.GroupModel", b =>
                {
                    b.HasOne("school_management_system.Models.ClassroomModel", null)
                        .WithMany("Groups")
                        .HasForeignKey("ClassroomModelId");
                });

            modelBuilder.Entity("school_management_system.Models.MajorModel", b =>
                {
                    b.HasOne("school_management_system.Models.DepartmentModel", null)
                        .WithMany("Majors")
                        .HasForeignKey("DepartmentModelId");

                    b.HasOne("school_management_system.Models.SubjectModel", null)
                        .WithMany("Major")
                        .HasForeignKey("SubjectModelId");
                });

            modelBuilder.Entity("school_management_system.Models.RoleModel", b =>
                {
                    b.HasOne("school_management_system.Models.AuthModel", null)
                        .WithMany("Roles")
                        .HasForeignKey("AuthModelId");
                });

            modelBuilder.Entity("school_management_system.Models.StudentModel", b =>
                {
                    b.HasOne("school_management_system.Models.AssessmentModel", null)
                        .WithMany("Students")
                        .HasForeignKey("AssessmentModelId");
                });

            modelBuilder.Entity("school_management_system.Models.SubjectModel", b =>
                {
                    b.HasOne("school_management_system.Models.AssessmentModel", null)
                        .WithMany("Subjects")
                        .HasForeignKey("AssessmentModelId");
                });

            modelBuilder.Entity("school_management_system.Models.AssessmentModel", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("school_management_system.Models.Assessment_TypeModel", b =>
                {
                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("school_management_system.Models.AuthModel", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("school_management_system.Models.ClassroomModel", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("school_management_system.Models.DepartmentModel", b =>
                {
                    b.Navigation("Majors");
                });

            modelBuilder.Entity("school_management_system.Models.StudentModel", b =>
                {
                    b.Navigation("Auths");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("school_management_system.Models.SubjectModel", b =>
                {
                    b.Navigation("Major");
                });

            modelBuilder.Entity("school_management_system.Models.TeacherModel", b =>
                {
                    b.Navigation("AuthModels");
                });
#pragma warning restore 612, 618
        }
    }
}
